# Global parameters
seed: 42
device: "cpu" # Options: "cpu", "cuda"

# Dataset configuration for training and validation
dataset:
  train:
    data_root: "/Users/mirzabicer/Projects/teknofest-2025/data/data/train"
    annotation_file: "/Users/mirzabicer/Projects/teknofest-2025/data/data/train/annotations.json"
    image_size: [128, 128]
    annotation_format: "json_coco" # Options: "json_coco", "txt_yolo", "custom_format"
    classes: ["red_circle", "black_square"]
    use_cache: false
    cache_backend: "ram" # Options: "ram", "disk"
    cache_dir: ".dataset_cache"
  val:
    data_root: "/Users/mirzabicer/Projects/teknofest-2025/data/data/train"
    annotation_file: "/Users/mirzabicer/Projects/teknofest-2025/data/data/train/annotations.json"
    image_size: [128, 128]
    annotation_format: "json_coco"
    classes: ["red_circle", "black_square"]
    use_cache: false
    cache_backend: "ram"
    cache_dir: ".dataset_cache"
  test:
    data_root: "/Users/mirzabicer/Projects/teknofest-2025/data/data/test"
    annotation_file: "/Users/mirzabicer/Projects/teknofest-2025/data/data/test/_annotations.coco.json"
    image_size: [128, 128]
    annotation_format: json_coco
    classes: ["red_circle", "black_square"]
    use_cache: false
    cache_backend: ram
    cache_dir: .dataset_cache

# Dataloader parameters
dataloader:
  batch_size: 16
  num_workers: 6
  pin_memory: true

# Model configuration
model:
  name: "simple_object_detector"
  input_channels: 3
  num_classes: 2
  grid_size: 7
  # Optional pretrained settings
  pretrained_path: "/Users/mirzabicer/Projects/teknofest-2025/outputs/2025-02-03/00-00-46/checkpoints/drone_object_detection_experiment/best_model.pth"
  pretrained_strict: true

# Loss function configuration (choose one: e.g., custom_loss, focal_loss, smooth_l1_loss, or cross_entropy)
loss:
  name: detection_loss
  alpha: 0.25
  gamma: 2.0
  cls_loss_weight: 1.0
  box_loss_weight: 10.0
  obj_loss_weight: 1.0
  grid_size: 7
  num_classes: 2
  bg_class: 0

# Optimizer configuration
optimizer:
  name: "adam"
  params:
    lr: 0.001
    weight_decay: 0.0001

# Learning rate scheduler configuration (optional)
lr_scheduler:
  name: "steplr"
  step_size: 10
  gamma: 0.1

# Metrics configuration (list of metric dictionaries) for now, one element: name: "iou", objectness_threshold: 0.5
metrics:
  - name: "detection_metrics"
    objectness_threshold: 0.5
    iou_threshold: 0.5
    conf_threshold: 0.5
    nms_iou_threshold: 0.5
    num_classes: 2

# Trainer configuration
trainer:
  name: "drone_object_detection"
  num_epochs: 10
  validation_freq_epochs: 1
  checkpoint_save_freq_epochs: 1
  experiment_name: "drone_object_detection_experiment"
  grad_clip_norm: 5.0
  tensorboard:
    enabled: true
    log_dir: "runs"
  mixed_precision:
    enabled: false

# (Optional) Profiling configuration
profiling:
  enabled: false
  schedule_wait: 1
  schedule_warmup: 1
  schedule_active: 1
  schedule_repeat: 1
  activities: ["cpu", "cuda"]
  record_shapes: false
  profile_memory: false
  with_stack: false
  trace_output_path: "profiler/profiler_trace.json"

tensorboard:
  enabled: true
  verbose: true
  log_every_batch: false # Log details for only sampled batches
  log_batch_sample_freq: 50 # Detailed logging every 50 batches (or first batch per epoch)
  log_memory: true
  log_exec_time: true
